"""expanding player table

Revision ID: 95ab489cde91
Revises: fec1a681825d
Create Date: 2022-08-19 16:38:54.063549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e984e1d01b'
down_revision = '95ab489cde91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return True
    # op.drop_column('player', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return True
    # ### end Alembic commands ###
