"""draft direction add

Revision ID: 8027a1ded1bf
Revises: 54e984e1d01b
Create Date: 2022-08-22 09:40:25.435613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8027a1ded1bf'
down_revision = '54e984e1d01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_status', sa.Column('DraftDirection', sa.Integer(), nullable=True))
    op.drop_column('player', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('value', sa.INTEGER(), nullable=True))
    op.drop_column('draft_status', 'DraftDirection')
    # ### end Alembic commands ###
