"""updating player table

Revision ID: 80a60f8d3a65
Revises: bbc8f8352474
Create Date: 2022-08-25 12:28:16.437192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a60f8d3a65'
down_revision = 'bbc8f8352474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('team', sa.String(length=5), nullable=True))
    op.add_column('player', sa.Column('draftrank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_player_draftrank'), 'player', ['draftrank'], unique=False)
    op.create_index(op.f('ix_player_ownership_group'), 'player', ['ownership_group'], unique=False)
    op.create_index(op.f('ix_player_pointprojection'), 'player', ['pointprojection'], unique=False)
    op.create_index(op.f('ix_player_team'), 'player', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_team'), table_name='player')
    op.drop_index(op.f('ix_player_pointprojection'), table_name='player')
    op.drop_index(op.f('ix_player_ownership_group'), table_name='player')
    op.drop_index(op.f('ix_player_draftrank'), table_name='player')
    op.drop_column('player', 'draftrank')
    op.drop_column('player', 'team')
    # ### end Alembic commands ###
