"""expanding player table

Revision ID: 95ab489cde91
Revises: fec1a681825d
Create Date: 2022-08-19 16:38:54.063549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ab489cde91'
down_revision = 'fec1a681825d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('tier', sa.String(length=5), nullable=True))
    op.add_column('player', sa.Column('pointprojection', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('vorpatdraft', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_player_tier'), 'player', ['tier'], unique=False)
    # op.drop_column('player', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('value', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_player_tier'), table_name='player')
    op.drop_column('player', 'vorpatdraft')
    op.drop_column('player', 'pointprojection')
    op.drop_column('player', 'tier')
    # ### end Alembic commands ###
