"""resetting

Revision ID: 9bba1a7999bc
Revises: 8027a1ded1bf
Create Date: 2022-08-22 09:55:49.002778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bba1a7999bc'
down_revision = '8027a1ded1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('player', 'value')
    # SQLlite doesn't like the normal drop column.
    with op.batch_alter_table('player') as batch_op:
        batch_op.drop_column('value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('value', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
