"""player ownership

Revision ID: fec1a681825d
Revises: 566245d7666a
Create Date: 2022-08-18 19:38:55.897264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec1a681825d'
down_revision = '566245d7666a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('ownership_group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'ownership_group')
    # ### end Alembic commands ###
